version: '3'

services:
  gogs:
    image: gogs/gogs:latest
    restart: always
    container_name: gogs
    ports:
    - "10022:22"
    - "3000:3000"
    environment:
    - TZ=Asia/Shanghai
    volumes:
    - "./data:/data"
